# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/weber/Dev/study/ipc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/weber/Dev/study/ipc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/weber/Dev/study/ipc/CMakeFiles /home/weber/Dev/study/ipc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/weber/Dev/study/ipc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named producer

# Build rule for target.
producer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 producer
.PHONY : producer

# fast build rule for target.
producer/fast:
	$(MAKE) -f shared_files/CMakeFiles/producer.dir/build.make shared_files/CMakeFiles/producer.dir/build
.PHONY : producer/fast

#=============================================================================
# Target rules for targets named consumer

# Build rule for target.
consumer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 consumer
.PHONY : consumer

# fast build rule for target.
consumer/fast:
	$(MAKE) -f shared_files/CMakeFiles/consumer.dir/build.make shared_files/CMakeFiles/consumer.dir/build
.PHONY : consumer/fast

#=============================================================================
# Target rules for targets named memwriter

# Build rule for target.
memwriter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memwriter
.PHONY : memwriter

# fast build rule for target.
memwriter/fast:
	$(MAKE) -f shared_memory/CMakeFiles/memwriter.dir/build.make shared_memory/CMakeFiles/memwriter.dir/build
.PHONY : memwriter/fast

#=============================================================================
# Target rules for targets named memreader

# Build rule for target.
memreader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memreader
.PHONY : memreader

# fast build rule for target.
memreader/fast:
	$(MAKE) -f shared_memory/CMakeFiles/memreader.dir/build.make shared_memory/CMakeFiles/memreader.dir/build
.PHONY : memreader/fast

#=============================================================================
# Target rules for targets named sender

# Build rule for target.
sender: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sender
.PHONY : sender

# fast build rule for target.
sender/fast:
	$(MAKE) -f message_queue/CMakeFiles/sender.dir/build.make message_queue/CMakeFiles/sender.dir/build
.PHONY : sender/fast

#=============================================================================
# Target rules for targets named receiver

# Build rule for target.
receiver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 receiver
.PHONY : receiver

# fast build rule for target.
receiver/fast:
	$(MAKE) -f message_queue/CMakeFiles/receiver.dir/build.make message_queue/CMakeFiles/receiver.dir/build
.PHONY : receiver/fast

#=============================================================================
# Target rules for targets named fifoReader

# Build rule for target.
fifoReader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fifoReader
.PHONY : fifoReader

# fast build rule for target.
fifoReader/fast:
	$(MAKE) -f pipes/CMakeFiles/fifoReader.dir/build.make pipes/CMakeFiles/fifoReader.dir/build
.PHONY : fifoReader/fast

#=============================================================================
# Target rules for targets named pipeUN

# Build rule for target.
pipeUN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pipeUN
.PHONY : pipeUN

# fast build rule for target.
pipeUN/fast:
	$(MAKE) -f pipes/CMakeFiles/pipeUN.dir/build.make pipes/CMakeFiles/pipeUN.dir/build
.PHONY : pipeUN/fast

#=============================================================================
# Target rules for targets named fifoWriter

# Build rule for target.
fifoWriter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fifoWriter
.PHONY : fifoWriter

# fast build rule for target.
fifoWriter/fast:
	$(MAKE) -f pipes/CMakeFiles/fifoWriter.dir/build.make pipes/CMakeFiles/fifoWriter.dir/build
.PHONY : fifoWriter/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f sockets/CMakeFiles/server.dir/build.make sockets/CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f sockets/CMakeFiles/client.dir/build.make sockets/CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named shutdown

# Build rule for target.
shutdown: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shutdown
.PHONY : shutdown

# fast build rule for target.
shutdown/fast:
	$(MAKE) -f signals/CMakeFiles/shutdown.dir/build.make signals/CMakeFiles/shutdown.dir/build
.PHONY : shutdown/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... producer"
	@echo "... consumer"
	@echo "... memwriter"
	@echo "... memreader"
	@echo "... sender"
	@echo "... receiver"
	@echo "... fifoReader"
	@echo "... pipeUN"
	@echo "... fifoWriter"
	@echo "... server"
	@echo "... client"
	@echo "... shutdown"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

